- www_src/locales.coffee
> Added Finnish locale.

- www/AppRate.js
- www_src/AppRate.coffee
- User will be redirected to rating view instead of app description
view in iOS App Store
- Use 1 universal url for all iOS versions
> Take user directly to rating view in iOS

- docs/class/AppRate.html
- docs/class/Locale.html
- docs/class/Locales.html
- typescript/AppRate.d.ts
In support of anyone using TypeScript combined with Cordova, I have
written the TypeScript definition file for this plugin :-)
> Adding TypeScript definition file

- www/AppRate.js
- www/locales.js
- www_src/AppRate.coffee
workaround for buttons not fitting :
https://github.com/pushandplay/cordova-plugin-apprate/issues/63
> change order of buttons

- README.md
[You can see the result here](https://github.com/rodrigograca31/cordova-plugin-apprate/tree/rodrigograca31-patch-2#available-preferences-options)
Thanks for the great extension!
> Makes the "Available preferences options" easier to read.

- CHANGELOG.md
- package.json
- plugin.xml
- www/AppRate.js
Hi,
As we are using tools that are checking the version inside the plugin.xml and they were not aligned, I updated it and bumped it. I also need to have a callbacks once the job is done in every cases, not showing or showing
> update the version of the config.xml and bump the version of the plugin

- www/AppRate.js
fix: handle click outside Android popup
> fix: handle click outside Android popup

- www/AppRate.js
> Use app store "?action=write-review" parameter

- www/AppRate.js
Details in
https://github.com/pushandplay/cordova-plugin-apprate/issues/157#issuecomment-359720953
> remove unused callback execution

- package.json
> Add Typescript types definition to package.json

- www/locales.js
updated the locale for german (`de` and `de-at`).
Seems the new entries need to be present to prevent crashes (see #218, #212)
> Update locale.js for german

- src/ios/CDVAppRate.m
I have a long delay before opening store product view page. It is not clear to users.
Please correct me if I am wrong.
> Displaying store view page before it loads

- www/locales.js
> fix(locale): ru & uk

- www/locales.js
> Eu language

- www/AppRate.js
Use `var` instead of `const` to fix #243
> Use `var` instead of `const` to fix #243

- www/locales.js
> Update Turkish Locale

- www/AppRate.js
This pull request makes this plugin work on Capacitor.
- Fixes #237
> Capacitor support

- www/AppRate.js
The `iOSRating` counter is not needed since Apple has its own mechanism in place for this.
https://developer.apple.com/documentation/storekit/skstorereviewcontroller/requesting_app_store_reviews
> However, you should be aware that the prompt will only be displayed to a user a maximum of three times within a 365-day period. 
Removing this check helps with developing (#242).
Because Apple doe not use this limit in development mode:
https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview#discussion
> When you call this method while your app is still in development mode, a rating/review request view is always displayed so that you can test the user interface and experience.
> Remove iOS rating counter in favor of native approach

- www/AppRate.js
please see https://github.com/ionic-team/ionic-framework/blob/ab1fc8f2311fd252146942c7a947ebc96efd054f/core/src/utils/platform.ts#L38
> fix for iPad ios13+

- www/AppRate.js
> [#298] change let to var

- www/locales.js
Hi! This PR add more meaningful translate string for portuguese Brazil.
> feat: add pt-BR translation

- www/locales.js
This diff is to prevent rendering issues on Android as the apostrophe does not show correctly in English.
> Fix apostrophe for English locale

- CHANGELOG.md
- src/ios/CDVAppRate.m
Solves #327 by wrapping the whole method in `dispatch_async(dispatch_get_main_queue(), ^{ do_the_stuff });`
Thanks to @jellomaster for suggesting the fix in the thread
> Fix error in IOS 17 in method launchAppStore
